# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/CA_LAB/CA_LAB.cache/wt [current_project]
set_property parent.project_path C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/CA_LAB/CA_LAB.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/CA_LAB/CA_LAB.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Files/output_ultimate.coe
read_verilog -library xil_defaultlib {
  C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/modules/IF/fetch_instruction.v
  C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/modules/IF/fetch_rf.v
  C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/modules/ID/condition_check.v
  C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/modules/ID/control_unit.v
  C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/modules/ID/register_file_id.v
  C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/modules/ID/id_top_module.v
  C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/modules/ID/id_rf.v
  C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/modules/EXE/ALU.v
  C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/modules/EXE/status_register.v
  C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/modules/EXE/val2generator.v
  C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/modules/EXE/top_module.v
  C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/modules/EXE/exe_rf.v
  C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/modules/Hazard/hazard.v
  C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/modules/MEM/mem_rf.v
  C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/modules/WB/mux32b.v
  C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/modules/forward/forward.v
  C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/CA_LAB/CA_LAB.srcs/sources_1/bd/CA_LAB1/hdl/CA_LAB1_wrapper.v
}
read_vhdl -library xil_defaultlib C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Files/debouncer.vhd
add_files C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/CA_LAB/CA_LAB.srcs/sources_1/bd/CA_LAB1/CA_LAB1.bd
set_property is_enabled true [get_files -all C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/CA_LAB/CA_LAB.srcs/sources_1/bd/CA_LAB1/ip/CA_LAB1_fetch_register_file_0_0/synth/CA_LAB1_fetch_register_file_0_0.v]
set_property used_in_implementation false [get_files -all c:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/CA_LAB/CA_LAB.srcs/sources_1/bd/CA_LAB1/ip/CA_LAB1_dist_mem_gen_0_1/CA_LAB1_dist_mem_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/CA_LAB/CA_LAB.srcs/sources_1/bd/CA_LAB1/ip/CA_LAB1_dist_mem_gen_0_0/CA_LAB1_dist_mem_gen_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/CA_LAB/CA_LAB.srcs/sources_1/bd/CA_LAB1/ip/CA_LAB1_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/CA_LAB/CA_LAB.srcs/sources_1/bd/CA_LAB1/ip/CA_LAB1_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/CA_LAB/CA_LAB.srcs/sources_1/bd/CA_LAB1/ip/CA_LAB1_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/CA_LAB/CA_LAB.srcs/sources_1/bd/CA_LAB1/ip/CA_LAB1_ila_0_0/CA_LAB1_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/CA_LAB/CA_LAB.srcs/sources_1/bd/CA_LAB1/ip/CA_LAB1_vio_0_0/CA_LAB1_vio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/CA_LAB/CA_LAB.srcs/sources_1/bd/CA_LAB1/ip/CA_LAB1_vio_0_0/CA_LAB1_vio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/CA_LAB/CA_LAB.srcs/sources_1/bd/CA_LAB1/CA_LAB1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/CA_LAB/pin_assignment.xdc
set_property used_in_implementation false [get_files C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/CA_LAB/pin_assignment.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top CA_LAB1_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CA_LAB1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CA_LAB1_wrapper_utilization_synth.rpt -pb CA_LAB1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
