# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/CA_LAB/pin_assignment.xdc

# Block Designs: bd/CA_LAB1/CA_LAB1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CA_LAB1 || ORIG_REF_NAME==CA_LAB1} -quiet] -quiet

# IP: bd/CA_LAB1/ip/CA_LAB1_fetch_instruction_0_0/CA_LAB1_fetch_instruction_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CA_LAB1_fetch_instruction_0_0 || ORIG_REF_NAME==CA_LAB1_fetch_instruction_0_0} -quiet] -quiet

# IP: bd/CA_LAB1/ip/CA_LAB1_xlslice_0_0/CA_LAB1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CA_LAB1_xlslice_0_0 || ORIG_REF_NAME==CA_LAB1_xlslice_0_0} -quiet] -quiet

# IP: bd/CA_LAB1/ip/CA_LAB1_fetch_register_file_0_0/CA_LAB1_fetch_register_file_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CA_LAB1_fetch_register_file_0_0 || ORIG_REF_NAME==CA_LAB1_fetch_register_file_0_0} -quiet] -quiet

# IP: bd/CA_LAB1/ip/CA_LAB1_dist_mem_gen_0_1/CA_LAB1_dist_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CA_LAB1_dist_mem_gen_0_1 || ORIG_REF_NAME==CA_LAB1_dist_mem_gen_0_1} -quiet] -quiet

# IP: bd/CA_LAB1/ip/CA_LAB1_id_top_module_0_0/CA_LAB1_id_top_module_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CA_LAB1_id_top_module_0_0 || ORIG_REF_NAME==CA_LAB1_id_top_module_0_0} -quiet] -quiet

# IP: bd/CA_LAB1/ip/CA_LAB1_id_register_file_0_0/CA_LAB1_id_register_file_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CA_LAB1_id_register_file_0_0 || ORIG_REF_NAME==CA_LAB1_id_register_file_0_0} -quiet] -quiet

# IP: bd/CA_LAB1/ip/CA_LAB1_top_ex_0_0/CA_LAB1_top_ex_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CA_LAB1_top_ex_0_0 || ORIG_REF_NAME==CA_LAB1_top_ex_0_0} -quiet] -quiet

# IP: bd/CA_LAB1/ip/CA_LAB1_ex_register_file_0_0/CA_LAB1_ex_register_file_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CA_LAB1_ex_register_file_0_0 || ORIG_REF_NAME==CA_LAB1_ex_register_file_0_0} -quiet] -quiet

# IP: bd/CA_LAB1/ip/CA_LAB1_data_hazard_unit_0_0/CA_LAB1_data_hazard_unit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CA_LAB1_data_hazard_unit_0_0 || ORIG_REF_NAME==CA_LAB1_data_hazard_unit_0_0} -quiet] -quiet

# IP: bd/CA_LAB1/ip/CA_LAB1_dist_mem_gen_0_0/CA_LAB1_dist_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CA_LAB1_dist_mem_gen_0_0 || ORIG_REF_NAME==CA_LAB1_dist_mem_gen_0_0} -quiet] -quiet

# IP: bd/CA_LAB1/ip/CA_LAB1_mem_register_file_0_0/CA_LAB1_mem_register_file_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CA_LAB1_mem_register_file_0_0 || ORIG_REF_NAME==CA_LAB1_mem_register_file_0_0} -quiet] -quiet

# IP: bd/CA_LAB1/ip/CA_LAB1_mux2to1_32bit_0_0/CA_LAB1_mux2to1_32bit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CA_LAB1_mux2to1_32bit_0_0 || ORIG_REF_NAME==CA_LAB1_mux2to1_32bit_0_0} -quiet] -quiet

# IP: bd/CA_LAB1/ip/CA_LAB1_xlslice_0_1/CA_LAB1_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CA_LAB1_xlslice_0_1 || ORIG_REF_NAME==CA_LAB1_xlslice_0_1} -quiet] -quiet

# IP: bd/CA_LAB1/ip/CA_LAB1_forward_0_0/CA_LAB1_forward_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CA_LAB1_forward_0_0 || ORIG_REF_NAME==CA_LAB1_forward_0_0} -quiet] -quiet

# IP: bd/CA_LAB1/ip/CA_LAB1_debouncer_0_0/CA_LAB1_debouncer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CA_LAB1_debouncer_0_0 || ORIG_REF_NAME==CA_LAB1_debouncer_0_0} -quiet] -quiet

# IP: bd/CA_LAB1/ip/CA_LAB1_ila_0_0/CA_LAB1_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CA_LAB1_ila_0_0 || ORIG_REF_NAME==CA_LAB1_ila_0_0} -quiet] -quiet

# IP: bd/CA_LAB1/ip/CA_LAB1_vio_0_0/CA_LAB1_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CA_LAB1_vio_0_0 || ORIG_REF_NAME==CA_LAB1_vio_0_0} -quiet] -quiet

# XDC: bd/CA_LAB1/ip/CA_LAB1_dist_mem_gen_0_1/CA_LAB1_dist_mem_gen_0_1_ooc.xdc

# XDC: bd/CA_LAB1/ip/CA_LAB1_dist_mem_gen_0_0/CA_LAB1_dist_mem_gen_0_0_ooc.xdc

# XDC: bd/CA_LAB1/ip/CA_LAB1_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CA_LAB1_ila_0_0 || ORIG_REF_NAME==CA_LAB1_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/CA_LAB1/ip/CA_LAB1_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CA_LAB1_ila_0_0 || ORIG_REF_NAME==CA_LAB1_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/CA_LAB1/ip/CA_LAB1_ila_0_0/CA_LAB1_ila_0_0_ooc.xdc

# XDC: bd/CA_LAB1/ip/CA_LAB1_vio_0_0/CA_LAB1_vio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CA_LAB1_vio_0_0 || ORIG_REF_NAME==CA_LAB1_vio_0_0} -quiet] -quiet

# XDC: bd/CA_LAB1/ip/CA_LAB1_vio_0_0/CA_LAB1_vio_0_0_ooc.xdc

# XDC: bd/CA_LAB1/CA_LAB1_ooc.xdc
