set_property SRC_FILE_INFO {cfile:C:/aidin/AIDIN/peregrine/term-6/gh_CaLab/CA_LAB/Vivado/V3/CA_LAB/pin_assignment.xdc rfile:../../../pin_assignment.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18                [get_ports clk]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14                [get_ports rst]
