spring.application.name=WealthWise

spring.artemis.mode=native
spring.artemis.host=localhost
spring.artemis.port=61616
spring.artemis.user=admin
spring.artemis.password=admin
app.messaging.capitalRaiseQueue=CAPITAL_RAISE.IN

#If using docker run artemis with : 
# docker run -d --name artemiscontainer   -p 61616:61616 -p 8161:8161   -e ARTEMIS_USER=admin -e ARTEMIS_PASSWORD=admin   
# -v artemis-data:/var/lib/artemis-instance   apache/activemq-artemis:latest-alpine 